### ISSUE TITLE
vload on `Matrix{Float64}`

### ISSUE THREAD

**Issue by algorithmx** [eschnett/SIMD.jl#116]
Dear developers,

I need to access a Julia matrix `M` of size `(4,ncol)`  via  `vload` function in a performance-critical situation, where converting the matrix `M` to a vector by `vec(M)` is prohibited. How can I properly use `vload` to access the k-th column of `M`, given that this matrix is properly padded (i.e. `all(M[4,:] .== 0) == true` )? If I cannot do this, from where can I extent the `vload` function?

#feature-request

**Comment by KristofferC** [comment]
Maybe:

```
julia> function load_column(x, i)
           GC.@preserve x begin
               ptr = pointer(x, 4*(i-1)+1)
               SIMD.vload(Vec{4, Float64}, ptr)
           end
       end
load_column (generic function with 1 method)

julia> x = rand(4, 10)
4×10 Matrix{Float64}:
 0.105425  0.112207   0.164943  0.924851     0.962439  0.771419   0.232943  0.0477578  0.31495   0.725615
 0.583358  0.574841   0.682031  0.0163499    0.889354  0.810443   0.343777  0.372169   0.841392  0.0536699
 0.831974  0.78172    0.424055  0.000215734  0.176126  0.177913   0.842223  0.706929   0.837163  0.591129
 0.567482  0.0297791  0.552873  0.123447     0.485557  0.0712733  0.925538  0.928424   0.719696  0.236411

julia> load_column(x, 1)
<4 x Float64>[0.10542510183253728, 0.5833583593228673, 0.8319741449401951, 0.5674824353491745]

julia> load_column(x, 5)
<4 x Float64>[0.9624389422624501, 0.8893543320414525, 0.17612558720563265, 0.4855567380042497]
```

**Comment by algorithmx** [comment]
> Maybe:
> 
> ```
> julia> function load_column(x, i)
>            GC.@preserve x begin
>                ptr = pointer(x, 4*(i-1)+1)
>                SIMD.vload(Vec{4, Float64}, ptr)
>            end
>        end
> load_column (generic function with 1 method)
> 
> julia> x = rand(4, 10)
> 4×10 Matrix{Float64}:
>  0.105425  0.112207   0.164943  0.924851     0.962439  0.771419   0.232943  0.0477578  0.31495   0.725615
>  0.583358  0.574841   0.682031  0.0163499    0.889354  0.810443   0.343777  0.372169   0.841392  0.0536699
>  0.831974  0.78172    0.424055  0.000215734  0.176126  0.177913   0.842223  0.706929   0.837163  0.591129
>  0.567482  0.0297791  0.552873  0.123447     0.485557  0.0712733  0.925538  0.928424   0.719696  0.236411
> 
> julia> load_column(x, 1)
> <4 x Float64>[0.10542510183253728, 0.5833583593228673, 0.8319741449401951, 0.5674824353491745]
> 
> julia> load_column(x, 5)
> <4 x Float64>[0.9624389422624501, 0.8893543320414525, 0.17612558720563265, 0.4855567380042497]
> ```

Thanks @KristofferC, problem solved! The performance difference is narrow for the two versions of my code, one with flattened matrix and the other with the original matrix plus your suggestion for `load_column(x, i)`. Here is the code I am working on and the benchmark on a 4x10 matrix.

![Screenshot from 2023-08-18 15-15-10](https://github.com/eschnett/SIMD.jl/assets/10635591/bb8943db-90b4-41db-8fa2-f84e015f6855)
![Screenshot from 2023-08-18 15-15-53](https://github.com/eschnett/SIMD.jl/assets/10635591/872dae49-64f7-43e7-80d5-6acec08b9e05)

**Comment by algorithmx** [comment]
`GC.@preserve` does the job. 
Reference:
https://docs.julialang.org/en/v1/base/base/#Base.GC.@preserve
https://docs.juliahub.com/ManualMemory/rywzg/0.1.8/
