### ISSUE TITLE
No type promotion for arithmetics of mixed types

### ISSUE THREAD

**Issue by favba** [eschnett/SIMD.jl#128]
Current behavior:
```
julia> a = Vec(1,2)
<2 x Int64>[1, 2]

julia> b = Vec(1.,2.)
<2 x Float64>[1.0, 2.0]

julia> a + b
ERROR: MethodError: no method matching +(::Vec{2, Int64}, ::Vec{2, Float64})
...

julia> a*b
ERROR: MethodError: no method matching *(::Vec{2, Int64}, ::Vec{2, Float64})
...
```

**Comment by KristofferC** [comment]
I think this is kind of intended. When you do SIMD stuff you want to be very explicit in my opinion and doing arithmetic between different number types is kind of rare in practice and in those cases you can always do the conversion explicitly.

**Comment by favba** [comment]
Makes sense.
And type promotion when adding a scalar already works:
```
julia> Vec(1.0,2.0) + 1
<2 x Float64>[2.0, 3.0]
```
So it is better to handle `Vec` conversions explicitly.
