### ISSUE TITLE
`reduce(min, Vec)` doesn't respect IEEE 754

### ISSUE THREAD

**Issue by Moelf** [eschnett/SIMD.jl#129]
```julia
julia> a = SIMD.Vec((1.0, 2.0, NaN, 0.5))
<4 x Float64>[1.0, 2.0, NaN, 0.5]

julia> reduce(min, a)
0.5

julia> reduce(min, [1.0, 2.0, NaN, 0.5])
NaN
```

**Comment by KristofferC** [comment]
Everything in this package gets punted to LLVM so this should be reported there.

**Comment by Moelf** [comment]
depends on what we want though -- https://llvm.org/docs/LangRef.html#llvm-implementation they do have one `minimum` as oppose to `minnum` that has this semantics

**Comment by KristofferC** [comment]
I think https://llvm.org/docs/LangRef.html#llvm-vector-reduce-fmaximum-intrinsic is the relevant intrinsics which only seems available on julia nightly (LLVM 18).

https://github.com/eschnett/SIMD.jl/pull/130
