### ISSUE TITLE
Support for dot-notation operators via specialized broadcast

### ISSUE THREAD

**Issue by oschulz** [eschnett/SIMD.jl#16]
SIMD.jl defines element-wise operations, e.g. `A + A`, but using a Julia v0.5-style `A .+ A` will currently fall back to slow generic implementations.

SIMD could provide specialized methods of `broadcast` (and `map`, too?) for supported primitive operations. This should automatically optimize dot-notations operators as well.

**Comment by eschnett** [comment]
One usually stores scalar values (not SIMD values) in collections, thus I haven't encountered this problem myself. I would be open to a patch.

**Comment by oschulz** [comment]
> One usually stores scalar values (not SIMD values) in collections

Oh, sorry, that's not what I meant. I meant doing things like `A .+ A` for `SIMD.Vec` itself (instead `A + A`), not for collections containing SIMD values. After all, `SIMD.Vec` is a `DenseArray`, and from that I understand, the official recommendation is to use the dot-notation for element-wise operations in the future (since Julia v0.5).

If you're open to a patch, I can try to put something together (may take a while, got to finish some other stuff first).

**Comment by eschnett** [comment]
I'd be happy to accept a patch that allows this new syntax in addition to the old one.

The main SIMD use case is to manually vectorize loop. There, one starts with a loop kernel that works e.g. on `Float64`, and the idea is to be able to switch from `Float64` to `Vec{Float64}` with as few changes as possible. Thus having to rewrite all `+` to `.+` would be too tedious.

**Comment by oschulz** [comment]
I just realized that my proposal may lead to problems with the upcoming fused broadcasting for binary operations.
