### ISSUE TITLE
Performance of subarrays

### ISSUE THREAD

**Issue by jw3126** [eschnett/SIMD.jl#23]
Performance is often degraded, when using views. Here is an example:

```julia
using SIMD
using BenchmarkTools

function myadd!(out, a,b)
    V = Vec{8,Float32}
    @assert size(a) == size(b) == size(out)
    for i in 1:8:length(a)
        av = vload(V,a,i)
        bv = vload(V,b,i)
        ov = av + bv
        vstore(ov, out, i)
    end
    out
end
```

```julia
a = b = out= randn(Float32,10^6)
@benchmark myadd!(out, a, b)
```
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     264.645 μs (0.00% GC)
  median time:      267.240 μs (0.00% GC)
  mean time:        272.489 μs (0.00% GC)
  maximum time:     1.529 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```
```julia
va = view(a,:)
vb = view(b, :) 
vout = view(out, :)
@benchmark myadd!(vout, va, vb)
```
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     367.993 μs (0.00% GC)
  median time:      382.777 μs (0.00% GC)
  mean time:        395.287 μs (0.00% GC)
  maximum time:     1.157 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

**Comment by vchuravy** [comment]
On 0.7

```
@benchmark myadd!(out, a, b)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     331.448 μs (100.13% CPU, 0.00% GC)
  median time:      340.726 μs (99.07% CPU, 0.00% GC)
  mean time:        349.260 μs (99.62% CPU, 0.00% GC)
  maximum time:     3.239 ms (96.94% CPU, 0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1
```

```
@benchmark myadd!(vout, va, vb)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     357.930 μs (100.11% CPU, 0.00% GC)
  median time:      382.909 μs (99.51% CPU, 0.00% GC)
  mean time:        501.744 μs (99.32% CPU, 0.00% GC)
  maximum time:     9.234 ms (96.46% CPU, 0.00% GC)
  --------------
  samples:          9788
  evals/sample:     1
```

So still a bit slower but of close enough.
You should also make sure that `a, b, out` do **not** alias each other. 
`a, b, out = rand` all reference to the same array, causing wrong results.

**Comment by jw3126** [comment]
Okay thanks! I was not aware, that aliasing could cause wrong results.

**Comment by tkf** [comment]
Pardon me for necroposting.  This makes me worried about my understanding of the aliasing issue.

> You should also make sure that `a, b, out` do **not** alias each other.

@vchuravy If I understand correctly, what we need to worry here is read-after-write dependency.  So, more refined rule would be that

* (1) No data of `a` are written before read; i.e.,

    * (1a) Memory region of `a` and `out` do not overlap _or_

    * (1b) `pointer(out) <= pointer(a)` holds

    _and_

* (2) Same for `b` and `out`.

In particular, `a` and `b` _can_ freely alias each other.

Is it correct?

**Comment by eschnett** [comment]
Yes, `a` and `b` can alias (or be the same), but must not alias `out`.

**Comment by tkf** [comment]
@eschnett Thanks for confirming that! Is (1b) OK? That is to say, can I use:

```julia
xs = a Vector from somewhere
a = @view xs[2:end]
out = @view xs[1:end-1]
```

**Comment by tkf** [comment]
Actually, I don't understand why the original code

```julia
a = b = out= randn(Float32,10^6)
```

was bad.  I can see that

```julia
xs = randn(Float32,10^6)
out = @view xs[2:end]
a = b = @view xs[1:end-1]
```

is incorrect as `xs[i]` is written via `out[i-1]` before it is read via `a[i]`.

Do SIMD load/store have weaker notion of temporal ordering or something?

**Comment by eschnett** [comment]
Some SIMD architectures have weird semantics when a SIMD vector crosses a cache line, i.e. when unaligned SIMD vectors are written. This is relevant if the array is not sufficiently aligned. `randn` probably aligns to 16 bytes, but 64 bytes might be necessary. If LLVM assumes the pointers do not alias, then the unaligned store might overwrite data "ahead" of it.

This is not an issue on x86 architectures, where unaligned accesses work quite efficiently.

I don't know whether LLVM assumes that these pointers are aliased or not. If this case is properly handled, then there is no problem.

**Comment by tkf** [comment]
Thank you very much for the detailed explanation!  How CPU cache works exactly still is mystery to me but now I know a bit more about where to start digging (although I'd be lazy until I need to use non-x86).

**Comment by eschnett** [comment]
The problem I mentioned (which, I believe, exists on Blue Gene/Q, but other non-x86 architectures might also be affected) has nothing to do with caching itself. Rather, when the CPU accesses memory, this doesn't happen byte-by-byte, but rather in a highly parallel manner. x86 CPU read and write whole cache lines (64 bytes) at a time. In this sense, memory has been SIMD-parallelized for quite some time.

**Comment by tkf** [comment]
Thanks for the additional info.  But it actually makes me a bit confused...  If it's not related to the cache per se, we don't need to care about it unless load and store instructions for SIMD vectors have some weaker guarantee (like non-temporal store), right?  On the other hand I can guess that if caching plays important role here then aliasing can be an issue (e.g., I can imagine that it would be a problem if the store of a SIMD vector crossing a cache line does not set the dirty bit of the next cache line.)

**Comment by eschnett** [comment]
As I mentioned, this has nothing to do with caching. The possible issue I raised is that the BG/Q architecture (?) doesn't have non-aligned SIMD store instructions. Thus the compiler might (might, but doesn't need to) use an aligned SIMD store instruction that writes "too much" data, under the assumption that the data that are overwritten will be set correctly in the next loop iteration.

This has nothing to do with caching, but is rather a constraint of the machine instructions that could lead the compiler to produce code that overwrites part of the result array, since this would be faster. I believe the llvm language standard would allow it. This is an optimization that a compiler might perform if it assumes the pointers are not aliased, and it will lead to wrong results if the pointers are aliased.

**Comment by tkf** [comment]
> Thus the compiler might (might, but doesn't need to) use an aligned SIMD store instruction that writes "too much" data, under the assumption that the data that are overwritten will be set correctly in the next loop iteration.

This clarifies my confusion.  I didn't realize that a store using unaligned pointer would be executed as a write to a memory region wider than the SIMD register.

**Comment by KristofferC** [comment]
Seems fixed now.
