### ISSUE TITLE
Perhaps make `Vec` not an `AbstractArray`.

### ISSUE THREAD

**Issue by KristofferC** [eschnett/SIMD.jl#35]
The fact that `Vec` is an `AbstractArray` means that most general operations on it will tend to just work, but will, of course, have terrible performance. In practice with using this library, there is always the fear of hitting the slow fallback. I don't really see much generic code written for `AbstractArray` to be useful for `Vec` so I would argue that removing the inheritance makes sense.

**Comment by fredrikekre** [comment]
Just for `Vec`?

**Comment by eschnett** [comment]
This sounds reasonable. I don't recall whether there was a particular reason I made `Vec` an `AbstractArray`, or whether this was just to state that it implements much of the respective interface (size, element type, indexing, etc.). Do you want to submit a pull request?
