### ISSUE TITLE
Segfault in vstorent (non-temporal write)

### ISSUE THREAD

**Issue by maxbennedich** [eschnett/SIMD.jl#48]
I'm quite excited about the new `vstorent` function (introduced in [this PR](https://github.com/eschnett/SIMD.jl/pull/46)), but just discovered that the example in that PR segfaults for smaller vectors on my machine. Example:
```julia
using SIMD

function fill_storent(aa::Array{Int32, 1})
    @inbounds for i in Int32(1):Int32(8):Int32(size(aa, 1))
        vstorent(i + Vec(tuple(Int32(0),Int32(1),Int32(2),Int32(3),Int32(4),Int32(5),Int32(6),Int32(7))),
            aa, i)
    end
    nothing
end
```
And unfortunately:
```julia
julia> fill_storent(Array{Int32}(undef, 200))
Segmentation fault: 11
```
Environment:
```julia
julia> versioninfo()
Julia Version 1.2.0-DEV.94
Commit fb47697195 (2019-01-04 16:56 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by nlw0** [comment]
I think you need to use aligned arrays. SIMD.jl allows you to create it with `valloc`. I'm not sure this is all there is to it, how exactly it should be aligned, or how to enforce it... Can you try and see if just using valloc solves it for you?

**Comment by maxbennedich** [comment]
Ah, yes you're right, that fixes it. And to maintain good performance, we then need to pass a `pointer` to `vstorent` instead of an array and index as in the example above. I used an alignment of 8 entries:
```julia
function test_nt!(a)
    v = Vec{4,Float64}((0, 1, 2, 3))
    for i = 0:(length(a)+3)>>2
        vstorent(4i + 1 + v, pointer(a, 4i + 1))
    end
end

a = zeros(Float64, 200)
test_nt!(a)  # segfault

a = valloc(Float64, 8, 200)
test_nt!(a)  # works fine
```
