### ISSUE TITLE
memfence needed for `vstorent`

### ISSUE THREAD

**Issue by jkozdon** [eschnett/SIMD.jl#49]
I do not know how to do this, but I think that if non-temporal stores are allowed (via #46), you need some sort of mem-fence for when the memory is needed again. The following code is the simplest way I could get to show this

```julia
using SIMD

"""
   copynt!(b, a)

copy `a` to `b` using 2 threads and 4-wide vector unit using nontemporal store
"""
function copynt!(b, a)
  Nhalf = div(length(a), 2)
  Threads.@threads for tid = 1:2
    n0 = (tid - 1) * Nhalf + 1
    n1 = tid*Nhalf
    for n = n0:4:n1-3
      aV = vloada(Vec{4, Float64}, a, n)
      vstorent(aV, b, n)
    end
  end
end

"""
   copya!(b, a)

copy `a` to `b` using 2 threads and 4-wide vector unit using temporal store
"""
function copya!(b, a)
  Nhalf = div(length(a), 2)
  Threads.@threads for tid = 1:2
    n0 = (tid - 1) * Nhalf + 1
    n1 = tid*Nhalf
    for n = n0:4:n1-3
      aV = vloada(Vec{4, Float64}, a, n)
      vstorea(aV, b, n)
    end
  end
end

function main(N)
  mod(N, 8) == 0 || error("N should be divisible by 8 (2 threads, 4-wide vector unit assumed)")
  a = valloc(Float64, div(32, sizeof(Float64)), N)
  b = valloc(Float64, div(32, sizeof(Float64)), N)

  a .= rand(N)

  b .= 0
  println("using `vstorea`")
  copya!(b, a)
  @show a == b
  println()

  b .= 0
  println("using `vstorent`")
  copynt!(b, a)
  @show a == b

  nothing
end

main(32)
```

which produces the following:

```
using `vstorea`
a == b = true

using `vstorent`
a == b = false
```

For bigger arrays the test passes, but I'm guessing this is because the check is happens sufficiently slow that things will be written before the check.

(Obviously this is a terrible use of nontemporal stores because the memory is used again right away, but still might be something worth considering for code safety/correctness reason.)

**Comment by jkozdon** [comment]
It's possible that what's needed is `fence seq_cst` which is what is available via `Threads.atomic_fence()`, so maybe the mem fence is already there; see <http://releases.llvm.org/6.0.0/docs/LangRef.html#fence-instruction>.

**Comment by eschnett** [comment]
Non-temporal stores leave the cache in a consistent state. When using a single thread, no fences are necessary.

When using multiple threads, then one needs to use fences or similar synchronization mechanisms. It can always be that the compiler accidentally generates code, or that the code accidentally runs in such a way that fences don't appear necessary. However, whether they are necessary is determined by LLVM's semantics, and those are modelled closely to C and C++, so fences are necessary.

The fact that they seem unnecessary without non-temporal stores is accidental. Things might be different with different array sizes, different timings, or on different architectures.

**Comment by jkozdon** [comment]
Thanks for the reply. I think that I understand the issue now. In a single threaded environment a read after a non-temporal store will always be OK, just perhaps slower since the value won't be in cache. Is that correct?

In the threaded case, the issue I'm seeing is just a classic race condition then.

**Comment by eschnett** [comment]
@jkozdon Yes, and yes.

**Comment by jkozdon** [comment]
Great. Will close the issue then. Thanks for your help.
