### ISSUE TITLE
Bounds check in vstore

### ISSUE THREAD

**Issue by nlw0** [eschnett/SIMD.jl#51]
I noticed this line is commented on similar functions, with a "todo". Should this be the same case? In this about implementing some missing mechanism to allow @inbounds propagation to work?
 https://github.com/eschnett/SIMD.jl/blob/124579752ddaebe7098dd1e6b91fea88d096adea/src/SIMD.jl#L1488

**Comment by eschnett** [comment]
I have not carefully implemented bounds checking. `SIMD` should, of course, check array bounds by default, even if I expect most application code to opt out. A mechanism that ensures that `@inbounds` is working would be most appreciated.

**Comment by nlw0** [comment]
I hope I can try implementing this some day, but right now I see myself having to use my own patched package so I can comment this. Shouldn't this perhaps be made similar to the other functions while the mechanism isn't properly implemented? Or maybe we can make a separate function in order to keep this one with the check?

**Comment by eschnett** [comment]
@nlw0 I don't understand what you are suggesting.

**Comment by KristofferC** [comment]
Just make sure you use this inside a `@inbounds` block and the boundscheck goes away (actually probably not on master due to https://github.com/JuliaLang/julia/issues/30411 but it should be fixed in https://github.com/eschnett/SIMD.jl/pull/63)
