### ISSUE TITLE
Separating/Moving the vectorized functions

### ISSUE THREAD

**Issue by aminya** [eschnett/SIMD.jl#59]
Is it possible to move the vectorized functions that this package provides to a separate file or repository? 

Now the vectorized library is mixed with other features that this package introduces (which are different things), and SIMD.jl has 2000 lines of code, which makes it hard for new developers to contribute.

It will help to add more functions to the library (and to hopefully merge it to Julia as a standard library later).

Personally, I am interested to contribute to this package by adding more functions.

**Comment by eschnett** [comment]
The file `SIMD.jl` has grown quite large. I'd be happy to split it into multiple files or sub-modules. I don't think it's worthwhile splitting it into multiple package yet.

**Comment by eschnett** [comment]
@KristofferC That also sounds like a good idea. `SIMD.jl` started as low-level interface, but has since then gathered a few convenience functions. Keeping these separate makes sense.

**Comment by aminya** [comment]
> 
> 
> The file `SIMD.jl` has grown quite large. I'd be happy to split it into multiple files or sub-modules. I don't think it's worthwhile splitting it into multiple package yet.

My idea is to write vectorized functions libraries similar to [VML.jl](https://github.com/JuliaMath/VML.jl) in Julia. So I thought separating things can help this.

**Comment by KristofferC** [comment]
I don't think it will really help, at least not in any meaningful way. Best to just start working instead.

**Comment by KristofferC** [comment]
Doesn't seem like there is anything concrete to do here.

**Comment by aminya** [comment]
But I think https://github.com/eschnett/SIMD.jl/pull/63 is a good move regarding this issue. Thank you for making that PR!
