### ISSUE TITLE
Operations with saturation/ceil 

### ISSUE THREAD

**Issue by davidbp** [eschnett/SIMD.jl#65]
Hello,

I could not find saturation operations implemented (maybe they are not there).

The standard + operator does
```julia
x = Vec(UInt8.((255,255,255,255)))
y = Vec(UInt8.((1,0,0,0)))
x + y
<4 x UInt8>[0, 255, 255, 255]
```

I would like to do  a `sum_ceil` that keeps the maximum value of the datatype in case of overflow or the min in case of underflow.

```julia
x = Vec(UInt8.((255,255,255,255)))
y = Vec(UInt8.((1,0,0,0)))
sum_ceil(x,y)  
<4 x UInt8>[255, 255, 255, 255]
```

According to  [intel_X86](http://datasheets.chipdb.org/Intel/x86/MMX/MMX/PRM_CHP5.HTM) there are specific instructions that do this (no need to check manually overflow etc..) in a single instruction call. Do you have plans to add them? Or are they there but I could not see them.

**Comment by KristofferC** [comment]
Yes, these exist in LLVM (https://llvm.org/docs/LangRef.html#saturation-arithmetic-intrinsics).

They could easily be added to https://github.com/eschnett/SIMD.jl/pull/63/files#diff-04c8d1e34d3b52bf0e6db708969277ecR127. I might do it soon unless I get beaten to it.

**Comment by davidbp** [comment]
Thanks for your fast answer Kristoffer,  I hope that you can manage to do it.  This is beyond the current knowledge that I have about the low level parts interfacing LLVM and Julia. Nevertheles I hope to be able to build upon this features once they are ready !.

**Comment by KristofferC** [comment]
Added in https://github.com/eschnett/SIMD.jl/pull/63/commits/e3321e54a8ccbbba2164ffebea9cfd8b914394cb (you need to use the branch for that PR for now).

```

julia> x = Vec(UInt8.((255,255,255,255)))
<4 x UInt8>[255, 255, 255, 255]

julia> y = Vec(UInt8.((1,0,0,0)))
<4 x UInt8>[1, 0, 0, 0]

julia> SIMD.add_saturate(x, y)
<4 x UInt8>[255, 255, 255, 255]
```
