### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by KristofferC** [eschnett/SIMD.jl#67]
https://github.com/eschnett/SIMD.jl/pull/63 has been on master for quite a while now so perhaps it is time to make a new release with it.

The question is if it should be a 3.0 or 2.9 release. I think the current version should be fairly non-breaking compared to the last one (looking at the few tests that needed changing) but I think there are some differences when it comes to when arithmetic on vector of Bools are allowed etc.

cc @tkf, @eschnett

**Comment by eschnett** [comment]
I'm happy to make a new release. I tend to strictly follow the SerVer rules: If there is a breaking change, it's a new major version, otherwise a minor version. Can you give an example of what arithmetic is now not allowed any more?

**Comment by KristofferC** [comment]
Bool isn't really considered an arithmetic type now:

```jl
julia> a = Vec(true, false, true, false)
<4 x Bool>[1, 0, 1, 0]

julia> a+a
ERROR: MethodError: no method matching +(::Vec{4,Bool}, ::Vec{4,Bool})
```

**Comment by eschnett** [comment]
I tend towards a major release then. Would you object?

**Comment by tkf** [comment]
(Just FWIW I'm OK with either choice)

**Comment by eschnett** [comment]
@KristofferC Do you want to do the honour of releasing 3.0?

**Comment by KristofferC** [comment]
Sure, thanks.
