### ISSUE TITLE
syntax error in bitcast

### ISSUE THREAD

**Issue by yihozhang** [eschnett/SIMD.jl#75]
The current definition for bitcast is something like the following
```julia
@generated function bitcast(::Type{T1}, x::T2) where {T1<:LT, T2<:LT}
    sT1, sT2 = sizeof(T1), sizeof(T2)
    if sT1 != sT2
        return :(error("size of conversion type ($T1: $sT1) must be equal to the vector type ($T2: $sT2)"))
    end
    s = """
    %2 = bitcast $(llvm_type(T2)) %0 to $(llvm_type(T1))
    ret $(llvm_type(T1)) %2
    """
    return :(
        $(Expr(:meta, :inline));
        Base.llvmcall($s, T1, Tuple{T2}, x)
    )
end
```
If we make a call like `SIMD.Intrinsics.bitcast(Int,0x1)`, it will errors out with `ERROR: UndefVarError: sT1 not defined`. (Well, though we expect such call to error out, it's not the expected way to error out...)

It turns out Julia will only escape one level out of string, so the value of `sT1` and `sT2` can't be obtained from the meta-level. The fix could be something like

```julia
if sT1 != sT2
    return quote
        sT1 = $sT1
        sT2 = $sT2
        error("size of conversion type ($T1: $sT1) must be equal to the vector type ($T2: $sT2)")
    end
end
```

**Comment by eschnett** [comment]
It would be simpler to call `error` instead of returning `:error` from the generated function:
```Julia
    if sT1 != sT2
       error("size of conversion type ($T1: $sT1) must be equal to the vector type ($T2: $sT2)")
    end
```

**Comment by KristofferC** [comment]
It's usually good not to cause side effects inside the generator part. That's why the code is the way it is.

**Comment by eschnett** [comment]
Yes, but we're aborting the whole program (by calling `error`). So it doesn't matter if the semantics of function calls is a bit weird.

**Comment by KristofferC** [comment]
From what I understand the generator is assumed to be pure and can be called arbitrary number of times etc. Seems best to just fix the bug here. I can do it soon if no one beats me to it.

**Comment by vchuravy** [comment]
`error` from within the generator will be ignored by Julia. So you won't get the error message.

**Comment by eschnett** [comment]
I don't think errors are ignored:

```Julia
julia> @generated f() = error("oops")
f (generic function with 1 method)

julia> f()
ERROR: oops
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] #s1#1 at ./REPL[13]:1 [inlined]
 [3] #s1#1(::Any) at ./none:0
 [4] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:527
 [5] top-level scope at REPL[14]:1
```
