### ISSUE TITLE
Segfault when calling LLVM from function

### ISSUE THREAD

**Issue by jakobnissen** [eschnett/SIMD.jl#78]
MWE:
```
using SIMD
const i16x8 = Vec{16, UInt8}
const C = i16x8(Tuple(1:16))

function pshufb(x::i16x8, mask::i16x8)
    ccall("llvm.x86.ssse3.pshuf.b.128", llvmcall, i16x8, (i16x8, i16x8), x, mask)
end

pshufb(C, i16x8(Tuple(1:16)))

f(x) = pshufb(C, x)

f(i16x8(Tuple(1:16))) # this segfaults
```
Note that it does not segfault when calling `pshufb` from global scope, only when calling `f`. I have no idea what causes this

**Comment by jakobnissen** [comment]
Perhaps a better question is: Is it possible to use `shufflevector` where the mask is not a compile time constant, but the "input vector" is?

**Comment by KristofferC** [comment]
I don't really see how this is related to SIMD.jl, you don't seem to use any functions from it.

**Comment by KristofferC** [comment]
> Is it possible to use shufflevector where the mask is not a compile time constant, but the "input vector" is?

See, https://llvm.org/docs/LangRef.html#shufflevector-instruction

> The third argument is a shuffle mask vector constant whose element type is i32. The mask vector elements must be constant integers or undef values.

**Comment by jakobnissen** [comment]
Maybe I'm completely confused here. I wanted to call `vpshufb` directly. This is called `llvm.x86.ssse3.pshuf.b.128`, so it is present in LLVM. Though I can't find it in the reference you just linked. The instruction should work for non-constant masks - indeed, it does work when I use the command directly.

Is there a reason this instruction is not in SIMD.jl? It is not possible to add - must `shufflevector` take 32-bit integers instead of 8-bit ones?  Or is that not guaranteed to work on an LLVM level, after all?

**Comment by KristofferC** [comment]
SIMD.jl provides the LLVM intrinsics for LLVM vectors. These are generic over the platform and it is up to LLVM to do instruction selection. If you want to call specific assembly instructions you have to do it manually, indeed.

**Comment by KristofferC** [comment]
A decent way to do this is to call the intrinsics in C++ and look at the LLVM IR output (e.g. https://godbolt.org/z/vBTDVy). And then check what the llvm output is for your call in Julia.

**Comment by jakobnissen** [comment]
I see. Okay, I'll do that. Thanks!
