### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by miguelraz** [eschnett/SIMD.jl#81]
Hello!
I think I'd like to try and take up implementing some of the llvm trigonometric intrinsics implementations, but can't find them online.
Is there a possible roadmap to work with?

**Comment by KristofferC** [comment]
Can you give some more context? Do you mean e.g. https://llvm.org/docs/LangRef.html#llvm-sin-intrinsic?

**Comment by miguelraz** [comment]
Sure @KristofferC , thanks for the prompt response.
This repo's README [states]https://github.com/eschnett/SIMD.jl#simd-vector-operations):
```
(Currently missing: exponent ldexp significand, many trigonometric functions)
```

I searched for them already in the LangRef link, but couldn't find a vector intrinsic for trigonometrics, or the `exponent ldexp significand` vector intrinsics either.

**Comment by miguelraz** [comment]
Grepping through the LangRef, these seem to be the missing methods when compared to the README:
```
- [ ] llvm.powi
- [ ] llvm.sin
- [ ] llvm.cos
- [ ] llvm.pow
- [ ] llvm.fabs
- [ ] llvm.minnum
- [ ] llvm.maxnum
- [ ] llvm.minimum
- [ ] llvm.maximum
- [ ] llvm.rint
- [ ] llvm.nearbyint
- [ ] llvm.round
- [ ] llvm.roundeven
```

**Comment by KristofferC** [comment]
> Grepping through the LangRef, these seem to be the missing methods when compared to the README:

A lot of those exist if you look at https://github.com/eschnett/SIMD.jl/blob/master/src/LLVM_intrinsics.jl.

**Comment by miguelraz** [comment]
Thanks, I updated the list of remaining intrinsics not yet in `LLVM_intrinsics.jl`.

**Comment by KristofferC** [comment]
Hm, I'm not sure what that list is for. The README mostly shows operations for the `Vec` and not the underlying intrinsics so `fadd` would be included in `+` etc. There could be a section for the intrinsic as well.

**Comment by miguelraz** [comment]
By list do you mean the one I posted just above or the one in the README?

I posted the list 3 comments above to see if it was desirable to implement those remaining vector intrinsics that are in the LangRef but not in this package.

**Comment by KristofferC** [comment]
Then I don't understand the list. It shows e.g. `fadd` but that one is here https://github.com/eschnett/SIMD.jl/blob/ee80c1573f441e76ff3d3ac839572ae2c0d9723d/src/LLVM_intrinsics.jl#L173.

**Comment by miguelraz** [comment]
Ah, I see. 
1.IIUC that is because `constrained.fadd != fadd`. [Constrained fadd](https://llvm.org/docs/LangRef.html#llvm-experimental-constrained-fadd-intrinsic) takes a rounding mode argument as well. Those may or may not make sense to worry about right now, given that its marked experimental and I don't know the support of directed foating point rounding operations through the Julia compilation pipeline. Happy these for later.
2. Would a PR for `llvm.roundeven` be welcome then?

**Comment by KristofferC** [comment]
Sure, sounds good. Is there a Julia equivalent function be to added for `Vec`?

**Comment by miguelraz** [comment]
Yes, `round`, with `RoundNearest`.
```julia-repl
julia> round(2.5, RoundNearest)
2.0
julia> round(2.5)
2.0
```
From the helpdocs on `RoundNearest`. 
```
  RoundNearest

  The default rounding mode. Rounds to the nearest integer, with ties (fractional values of 0.5) being rounded to the nearest even integer.
```


Their LangRef:
```
This function returns the same values as the libm round functions would, and handles error conditions in the same way.
...
The ‘llvm.roundeven.*’ intrinsics returns the operand rounded to the nearest integer in floating-point format rounding halfway cases to even (that is, to the nearest value that is an even integer).
```
My googling skills [tell me that](https://reviews.llvm.org/D75670) `roundeven` always implements the `RoundNearest`, and `round` may implement a different rounding mode depending on the environment.

**Comment by miguelraz** [comment]
Updated the list with the `llvm.experimental.vector.insert/extract` intrinsics.

**Comment by KristofferC** [comment]
Things can further be discussed here but it doesn't seem to have an actionable thing to do from the maintainers, so closing this.

**Comment by miguelraz** [comment]
Fair enough, thanks for the followthrough.
