### ISSUE TITLE
carry intrinsics?

### ISSUE THREAD

**Issue by Seelengrab** [eschnett/SIMD.jl#90]
I'm surprised to see that the carry intrinsics (e.g. adding with carry, I think it's called `@llvm.x86.addcarry.64`) are not available here. Are they provided in some other package and I've just missed them?

I'd be happy to add them, but I've never worked with LLVM intrinsics before, so I'd be happy about some guidance.

**Comment by Seelengrab** [comment]
Looking through https://releases.llvm.org/2.8/docs/LangRef.html, I can't seem to find them at all - I thought LLVM had these 🤔

**Comment by KristofferC** [comment]
Are you talking about an architecture-specific intrinsic (which is a quite different thing from an LLVM intrinsic)

See some discussion about that here: https://github.com/eschnett/SIMD.jl/pull/89#issuecomment-886469682

**Comment by Seelengrab** [comment]
Very much possible! Thanks for the pointer.

**Comment by eschnett** [comment]
@Seelengrab I'd be happy to have generic add-with-carry functions in SIMD.jl. However, these need to work on (and be reasonably efficient on) all architectures. You would use the architecture-specific intrinsics if they are available, but a generic fallback needs to exist.

If I recall correctly, the condition for "overflow" (i.e. "carry is set") is (when adding):
- both summands have the same sign
- the sum has a different sign

This can be implemented with respective exclusive or statements. This code might work for 32-bit signed integers (`r` holds the result of the addition, `c` is the outgoing carry):
`r = s1 + s2`
`c = (~(s1 ⊻ s2) & (r ⊻ s1)) >> 31`
